### ISSUE TITLE
8 spaces indentation? Blasphemy!

### ISSUE THREAD

**Issue by predragmandic** [fantastic001/pydokuwiki#9]
self explanatory

**Comment by fantastic001** [comment]
Why is 8 spaces wrong? It is not pep8 standard but that kind of refactoring takes too much effort for nothing special at all.

**Comment by predragmandic** [comment]
So you are openly oposing pep8?? If it was good old 16th century, you would burn at the stake by now!
(sory, just trolling in the name of pep8 dogma :)
